// <auto-generated />
namespace Murtain.OAuth2.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03));
        
        string IMigrationMetadata.Id
        {
            get { return "201702020839300_03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
